fix(iOS): allow selecting visionOS simulator
wusyong/cargo-mobile pull request #208
Opened 2023-09-11 11:07 UTC by CrabNejonas

This fixes the simulator target selection incorrectly filtering out the visionOS target (it's just iPadOS after all).

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri-mobile/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information

2023-09-11 11:19 UTC, lucasfernog requested changes
just missing a change file :)

2023-09-19 09:18 UTC, CrabNejonas commented
> just missing a change file :)

Done!

2023-09-19 10:02 UTC, wusyong approved these changes

2023-09-19 18:34 UTC, lucasfernog approved these changes

2023-09-19 18:34 UTC, merged