fix: set `TARGET_CC` env var on Windows using unix spearator
wusyong/cargo-mobile pull request #42
Opened 2022-09-10 13:56 UTC by amrbashir

this helps cross-compliation

2022-09-12 13:52 UTC, lucasfernog requested changes

2022-09-12 13:52 UTC, lucasfernog commented on src/android/target.rs
> +            .compiler_path(ndk::Compiler::Clang, self.clang_triple(), min_sdk_version)
```suggestion
            .compiler_path(ndk::Compiler::Clangxx, self.clang_triple(), min_sdk_version)
```

2022-09-12 13:52 UTC, lucasfernog commented on src/android/target.rs
> +            .compiler_path(ndk::Compiler::Clang, self.clang_triple(), min_sdk_version)
```suggestion
            .compiler_path(ndk::Compiler::Clangxx, self.clang_triple(), min_sdk_version)
```

2022-09-14 18:17 UTC, Ludea commented
I just test your PR, the latest `/` is missing
https://github.com/Ludea/tauri-mobile/actions/runs/3054766151/jobs/4927396987#step:16:366

2022-09-14 18:19 UTC, amrbashir commented
yeah it seems like an issue upstream and we can't fix it here. I will probably close this PR since it fixed nothing

2022-09-14 18:31 UTC, Ludea commented
maybe changing https://github.com/tauri-apps/cargo-mobile/blob/dev/src/os/linux/mod.rs#L191 to `pub const CLANG: &str = "/clang";` can help ?

2022-09-14 18:33 UTC, amrbashir commented
I don't think so plus it could break cross-compilation in other places

2022-11-06 14:03 UTC, closed without merging