feat: add support for android studio which installed by jetbrains toolbox
wusyong/cargo-mobile pull request #88
Opened 2023-02-06 17:48 UTC by cxgreat2014

2023-02-06 21:36 UTC, amrbashir requested changes
Thanks, could you add a change file? see this https://github.com/tauri-apps/tauri-mobile/blob/dev/.changes/readme.md

2023-02-07 06:01 UTC, cxgreat2014 commented
Seems like I'm the first one to do this...I'm confused about the package name in the change file, could you please provide an example?

2023-02-07 15:41 UTC, amrbashir commented
it looks something like this
```md
---
"tauri-mobile": patch
---

Change summary here
```

2023-02-07 16:17 UTC, cxgreat2014 commented
Like this?

Add_open_support_for_Andriod_Studio.md
```markdown
---
"tauri-mobile": patch
---

Added open support for Android Studio installed by JetBrains Toolbox
```

2023-02-07 16:24 UTC, amrbashir commented
just needs a slight word change 
```md
---
"tauri-mobile": patch
---

Added support for opening Android Studio installed by JetBrains Toolbox
```

thanks

2023-02-07 16:33 UTC, cxgreat2014 commented
Added, Thanks~

2023-02-07 16:34 UTC, amrbashir approved these changes

2023-02-07 16:48 UTC, merged